## ДЗ Урок 2

### Задача 1
Контрольная работа состоит из пяти вопросов. На каждый вопрос приведено четыре варианта ответа, один из которых правильный. Составьте закон распределения числа правильных ответов при простом угадывании. Найдите M(X), D(X).

In [1]:
import numpy as np

In [2]:
x_values = np.arange(1, 6) # 5 вопросов в тесте

print(x_values)

[1 2 3 4 5]


В каждом вопросе 4 варианта ответа, один из которых правильный, рассчитаем вероятность к каждому значению x_values

In [3]:
x_probabilities = np.array([0.25, 0.25 ** 2, 0.25 ** 3, 0.25 ** 4, 0.25 ** 5])

print(x_probabilities)

[0.25       0.0625     0.015625   0.00390625 0.00097656]


Для рассчета математического ожидания перемножим поэлементно два получиввшихся массива и сложим результаты

In [4]:
m = x_values.dot(x_probabilities)

print(m)

0.4423828125


Для расчета дисперсии определим случайную величину, возведем её в квадрат и найдем её мат. ожидание.

In [6]:
y_values = x_values - m

print(y_values)

[0.55761719 1.55761719 2.55761719 3.55761719 4.55761719]


In [7]:
z_values = y_values ** 2

print(z_values)

[ 0.31093693  2.4261713   6.54140568 12.65664005 20.77187443]


In [8]:
d = z_values.dot(x_probabilities)

print(d)

0.401304435916245


Среднеквадратичное отклонение

In [9]:
np.math.sqrt(d)

0.6334859397936509

### Задача 2
Вероятность попадания в цель при одном выстреле равна 0.01. Какова вероятность того, что число попаданий при 200 выстрелах будет не менее 5 и не более 10?

Для решения задачи воспользуемся формулой Пуассона: $$P(X = k) = \dfrac{a^k e ^{-a}}{k!}.$$

In [10]:
def poisson_proba(k, lambda_):
    
    return (lambda_ ** k) * (np.exp(-lambda_)) / np.math.factorial(k)